// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYnuRzYqvMkVlqCfVWIRMXJ90INctXXo4',
    appId: '1:793322217460:web:28ea26b435d05d1e05a3a1',
    messagingSenderId: '793322217460',
    projectId: 'app-movies-f8a8c',
    authDomain: 'app-movies-f8a8c.firebaseapp.com',
    storageBucket: 'app-movies-f8a8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANRzQKCQmCDSmlIy1RM-DSImmvIraqH24',
    appId: '1:793322217460:android:3f0cece5a6560ad905a3a1',
    messagingSenderId: '793322217460',
    projectId: 'app-movies-f8a8c',
    storageBucket: 'app-movies-f8a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBXP35cYYBnHbQb53c8SEHllrSrDMB_GA',
    appId: '1:793322217460:ios:e8fd3e6c35e6079f05a3a1',
    messagingSenderId: '793322217460',
    projectId: 'app-movies-f8a8c',
    storageBucket: 'app-movies-f8a8c.firebasestorage.app',
    iosBundleId: 'com.example.appMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBXP35cYYBnHbQb53c8SEHllrSrDMB_GA',
    appId: '1:793322217460:ios:e8fd3e6c35e6079f05a3a1',
    messagingSenderId: '793322217460',
    projectId: 'app-movies-f8a8c',
    storageBucket: 'app-movies-f8a8c.firebasestorage.app',
    iosBundleId: 'com.example.appMovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYnuRzYqvMkVlqCfVWIRMXJ90INctXXo4',
    appId: '1:793322217460:web:8ead1f3f20f0c72405a3a1',
    messagingSenderId: '793322217460',
    projectId: 'app-movies-f8a8c',
    authDomain: 'app-movies-f8a8c.firebaseapp.com',
    storageBucket: 'app-movies-f8a8c.firebasestorage.app',
  );

}